# Copyright 2023 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

visibility("private")

DEFAULT_BUILD_FILE_GENERATION_BY_PATH = {
    "github.com/grpc-ecosystem/grpc-gateway/v2": "update",
}

DEFAULT_DIRECTIVES_BY_PATH = {
    "github.com/grpc-ecosystem/grpc-gateway": [
        "gazelle:resolve go github.com/grpc-ecosystem/grpc-gateway/internal //internal:go_default_library",
        "gazelle:go_naming_convention import_alias",
        "gazelle:proto disable",
    ],
    "github.com/pseudomuto/protoc-gen-doc": [
        # The build file in github.com/mwitkow/go-proto-validators has both go_proto and gogo_proto targets, but the checked
        # in go files are generated by gogo proto. Resolving to the gogo proto target preserves the behavior of Go modules.
        "gazelle:resolve go github.com/mwitkow/go-proto-validators @com_github_mwitkow_go_proto_validators//:validators_gogo",
    ],
    "k8s.io/apimachinery": [
        "gazelle:go_generate_proto false",
        "gazelle:proto_import_prefix k8s.io/apimachinery",
    ],
    "storj.io/common": [
        "gazelle:proto legacy",
    ],
    "storj.io/eventkit": [
        "gazelle:proto legacy",
    ],
    "storj.io/picobuf": [
        "gazelle:proto legacy",
    ],
}

DEFAULT_BUILD_EXTRA_ARGS_BY_PATH = {
    "github.com/census-instrumentation/opencensus-proto": [
        "-exclude=src",
    ],
    "github.com/cronokirby/saferith": [
        # This test file declares `package big` rather than `package saferith`.
        "-exclude=arith_s390x_test.go",
    ],
}
