load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_file",
)
load(
    "//internal:go_repository_cache.bzl",
    "go_repository_cache",
)
load(
    "//internal:go_repository_tools.bzl",
    "go_repository_tools",
)
load(
    "//internal:go_repository_config.bzl",
    "go_repository_config",
)

def _non_module_deps_impl(module_ctx):
    go_repository_cache(
        name = "bazel_gazelle_go_repository_cache",
        # Always provided by rules_go.
        go_sdk_name = "go_default_sdk",
        go_env = {},
    )
    go_repository_tools(
        name = "bazel_gazelle_go_repository_tools",
        go_cache = Label("@bazel_gazelle_go_repository_cache//:go.env"),
    )
    go_repository_config(
        name = "bazel_gazelle_go_repository_config",
        # Generated by the go_dep module extension.
        config = Label("@bazel_gazelle_go_repository_directives//:WORKSPACE"),
    )

    http_file(
        name = "buildozer_macos_arm",
        urls = ["https://github.com/bazelbuild/buildtools/releases/download/5.0.1/buildozer-darwin-arm64"],
        sha256 = "1d8a3b0e3a702630d36de012fd5cf93342af0fa1b5853643b318667345c84df0",
        downloaded_file_path = "buildozer",
        executable = True,
    )

    http_file(
        name = "buildozer_macos_x86",
        urls = ["https://github.com/bazelbuild/buildtools/releases/download/5.0.1/buildozer-darwin-amd64"],
        sha256 = "17a093596f141ead6ff70ac217a063d7aebc86174faa8ab43620392c17b8ee61",
        downloaded_file_path = "buildozer",
        executable = True,
    )

    http_file(
        name = "buildozer_linux_x86",
        urls = ["https://github.com/bazelbuild/buildtools/releases/download/5.0.1/buildozer-linux-amd64"],
        sha256 = "78204dac0ac6a94db499c57c5334b9c0c409d91de9779032c73ad42f2362e901",
        downloaded_file_path = "buildozer",
        executable = True,
    )

non_module_deps = module_extension(
    _non_module_deps_impl,
)
