// Generated by language/proto/gen/gen_known_imports.go
// From language/proto/proto.csv

package proto

import "github.com/bazelbuild/bazel-gazelle/label"

var knownProtoImports = map[string]label.Label{

	"google/protobuf/any.proto":             label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "any_go_proto"},
	"google/protobuf/api.proto":             label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "api_go_proto"},
	"google/protobuf/compiler/plugin.proto": label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "compiler_plugin_go_proto"},
	"google/protobuf/descriptor.proto":      label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "descriptor_go_proto"},
	"google/protobuf/duration.proto":        label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "duration_go_proto"},
	"google/protobuf/empty.proto":           label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "empty_go_proto"},
	"google/protobuf/field_mask.proto":      label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "field_mask_go_proto"},
	"google/protobuf/source_context.proto":  label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "source_context_go_proto"},
	"google/protobuf/struct.proto":          label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "struct_go_proto"},
	"google/protobuf/timestamp.proto":       label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "timestamp_go_proto"},
	"google/protobuf/type.proto":            label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "type_go_proto"},
	"google/protobuf/wrappers.proto":        label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "wrappers_go_proto"},
}
