// Generated by language/proto/gen/gen_known_imports.go
// From language/proto/proto.csv

package proto

import "github.com/bazelbuild/bazel-gazelle/label"

var knownGoProtoImports = map[string]label.Label{

	"github.com/golang/protobuf/ptypes/any":               label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "any_go_proto"},
	"google.golang.org/genproto/protobuf/api":             label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "api_go_proto"},
	"github.com/golang/protobuf/protoc-gen-go/plugin":     label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "compiler_plugin_go_proto"},
	"github.com/golang/protobuf/protoc-gen-go/descriptor": label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "descriptor_go_proto"},
	"github.com/golang/protobuf/ptypes/duration":          label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "duration_go_proto"},
	"github.com/golang/protobuf/ptypes/empty":             label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "empty_go_proto"},
	"google.golang.org/genproto/protobuf/field_mask":      label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "field_mask_go_proto"},
	"google.golang.org/genproto/protobuf/source_context":  label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "source_context_go_proto"},
	"github.com/golang/protobuf/ptypes/struct":            label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "struct_go_proto"},
	"github.com/golang/protobuf/ptypes/timestamp":         label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "timestamp_go_proto"},
	"google.golang.org/genproto/protobuf/ptype":           label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "type_go_proto"},
	"github.com/golang/protobuf/ptypes/wrappers":          label.Label{Repo: "io_bazel_rules_go", Pkg: "proto/wkt", Name: "wrappers_go_proto"},
}
